copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch).lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)1.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)2.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)3.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)4.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)5.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)6.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch).lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)7.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)8.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)9.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)4.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)5.lnk"
copy "1.lnk" "../四川省图书馆书目检索系统(with book cover patch)6.lnk"
exit